//
//  TestReactView.m
//  GJSNativeModuleExample
//
//  Created by GJS on 2017/4/1.
//  Copyright © 2017年 forp. All rights reserved.
//

#import "TestReactView.h"
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation TestReactView

- (instancetype)initWithFrame:(CGRect)frame {
  if (self == [super initWithFrame:frame]) {
    //[self loadReact];
  }
  return self;
}

- (instancetype)initWithCoder:(NSCoder *)coder
{
  self = [super initWithCoder:coder];
  if (self) {
    //[self loadReact];
  }
  return self;
}

-(void)layoutSubviews {
  [super layoutSubviews];
  [self loadReact];
}

-(void)loadReact {
  NSURL *jsCodeLocation = [NSURL URLWithString:@"http://10.23.90.147:8081/index.ios.bundle?platform=ios"];
  // For production use, this `NSURL` could instead point to a pre-bundled file on disk:
  //
  //   NSURL *jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
  //
  // generated by "Bundle React Native code and images" build step.
  //
  //   curl http://localhost:8081/index.ios.bundle -o main.jsbundle
  
#ifdef DEBUG
  [[RCTBundleURLProvider sharedSettings] setDefaults];
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
#else
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
#endif
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"TestReactNativeModule"
                                               initialProperties:nil
                                                   launchOptions:nil];
  [self addSubview:rootView];
  rootView.frame = self.bounds;
}

/*
// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
- (void)drawRect:(CGRect)rect {
    // Drawing code
}
*/

@end
